---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 3.1.0
  - name: community.docker
    version: 3.11.0
  - name: community.library_inventory_filtering_v1
    version: 1.0.1
  - name: kubernetes.core
    version: 3.0.1
