# Generated by Django 5.0.7 on 2024-07-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0008_list_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
