# Generated by Django 4.2.7 on 2024-08-04 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lists", "0009_alter_item_options_alter_item_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
